// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB14TLO3DCEC-K-RdyMnuvmn_yn7C2vYEw',
    appId: '1:129980351510:web:128f5c756bf3bce6246137',
    messagingSenderId: '129980351510',
    projectId: 'delivery-app-c453c',
    authDomain: 'delivery-app-c453c.firebaseapp.com',
    storageBucket: 'delivery-app-c453c.appspot.com',
    measurementId: 'G-1MRP11T93G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf0EEjkaT75XId7iOnccWA69ncZ-oLJxo',
    appId: '1:129980351510:android:9f1c15fd66358d7f246137',
    messagingSenderId: '129980351510',
    projectId: 'delivery-app-c453c',
    storageBucket: 'delivery-app-c453c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2QWQgSiMTu0BfX2snAaFn7CxMXbpO6xM',
    appId: '1:129980351510:ios:6eaaa5efb1ed552e246137',
    messagingSenderId: '129980351510',
    projectId: 'delivery-app-c453c',
    storageBucket: 'delivery-app-c453c.appspot.com',
    iosClientId: '129980351510-3qf4500bv9gcar4b6js9csmcgb10h1fg.apps.googleusercontent.com',
    iosBundleId: 'mehani.sim.deliveryApp',
  );
}
